package com.businessanalysis.businessanalysisai.entity;

public enum ActivityAction {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    ANALYSIS_STARTED,
    ANALYSIS_COMPLETED,
    ANALYSIS_FAILED,
    REQUIREMENTS_GENERATED,
    USER_STORIES_GENERATED,
    DOCUMENTATION_GENERATED,
    AI_CHAT_INTERACTION
}
